name: Build-Dev

on:
  workflow_dispatch:  # 使用 workflow_dispatch 事件触发
  # pull_request:
  #   branches: [ "main" ]
  # push:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        uses: docker/login-action@v3.3.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: FetchTimestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date '+%y%m%d')" >> $GITHUB_ENV

      - name: FetchGitHash
        id: git-hash
        run: echo "GIT_HASH=$(git rev-parse HEAD | cut -c1-4)" >> $GITHUB_ENV

      - name: SetEnvVar
        run: |
           echo "IMAGE_VERSION=${{ env.TIMESTAMP }}-${{ env.GIT_HASH }}" >> $GITHUB_ENV
           echo "IMAGE_TAG=slim-${{ env.TIMESTAMP }}-${{ env.GIT_HASH }}" >> $GITHUB_ENV

      - name: ECHO IMAGE_TAG
        run: echo $IMAGE_TAG

      - name: BuildDockerImage
        run: cd ./3.9/slim-bullseye && docker build -t standardcore/python-ffmpeg:${{ env.IMAGE_TAG }} .

      - name: PushDockerImage
        run: docker push standardcore/python-ffmpeg:${{ env.IMAGE_TAG }} .
